import { Inter } from "next/font/google";

import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "DL Food",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const current = 'customer';
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="padding-root border-b-2 "><Header /></header>
        <main className="padding-root">{children}</main>
        <footer className="padding-root"><Footer /></footer>
      </body>
    </html>
  );
}
